import '../services/sharedpref_service.dart';

class AppText {
  static const Map<String, Map<String, String>> _values = {
    'id': {
      'settings': 'Pengaturan',
      'dashboard': 'Dashboard',
      'planner': 'Planner',
      'more': 'Lainnya',
      'welcomeBack': 'Selamat datang kembali di StudySync',
      'semesterProgress': 'Progress Semester',
      'keepPerformance': 'Pertahankan kinerja akademismu!',
      'totalTasks': 'Total Tugas',
      'completed': 'Selesai',
      'pending': 'Pending',
      'weeklyProductivity': 'Produktivitas Mingguan',
      'plannerDesc': 'Atur dan selesaikan agenda harianmu',
      'moreDesc': 'Fitur tambahan untuk mendukung belajarmu',
      'tasks': 'Tugas',
      'taskDesc': 'Kelola tugas dan deadline kuliah',
      'schedule': 'Jadwal',
      'scheduleDesc': 'Jadwal kuliah dan kegiatan',
      'notes': 'Catatan',
      'notesDesc': 'Catatan penting dan ide kreatif',
      'habits': 'Kebiasaan',
      'habitsDesc': 'Bangun kebiasaan produktif harian',
      'courseTarget': 'Target Mata Kuliah',
      'studySession': 'Sesi Belajar',
      'reviewMateri': 'Review Materi',
      'pomodoroShort': 'Pomodoro',
      'display': 'Tampilan',
      'darkMode': 'Mode Gelap',
      'focusSecurity': 'Notifikasi & Fokus',
      'notifications': 'Notifikasi Aplikasi',
      'focusMode': 'Mode Fokus',
      'focusModeDesc': 'Kurangi gangguan saat sesi belajar',
      'language': 'Bahasa',
      'chooseLanguage': 'Pilih Bahasa',
      'resetDefault': 'Reset Ke Default',
      'profile': 'Profil',
      'username': 'Nama Pengguna',
      'activeSemester': 'Semester Aktif',
      'saveProfile': 'Simpan Profil',
      'pickPhoto': 'Pilih Foto',
      'removePhoto': 'Hapus Foto',
      'profileUpdated': 'Profil berhasil diperbarui',
      'pomodoro': 'Pomodoro Timer',
      'focusActive': 'MODE FOKUS AKTIF',
      'focusDisabled': 'Fast forward dinonaktifkan saat Mode Fokus aktif',
      'all': 'Semua',
      'noTasks': 'Tidak ada tugas',
      'edit': 'Edit',
      'delete': 'Hapus',
      'taskDeleted': 'Tugas berhasil dihapus',
      'addTask': 'Tambah Tugas',
      'editTask': 'Edit Tugas',
      'taskTitle': 'Judul Tugas',
      'taskTitleHint': 'Masukkan judul tugas...',
      'description': 'Deskripsi',
      'taskDescHint': 'Masukkan rincian tugas (opsional)...',
      'dueDate': 'Tenggat Waktu',
      'priority': 'Prioritas',
      'category': 'Kategori',
      'saveTask': 'Simpan Tugas',
      'saveChanges': 'Simpan Perubahan',
      'taskAdded': 'Tugas berhasil ditambahkan',
      'taskUpdated': 'Tugas berhasil diperbarui',
      'selectScheduleOptional': 'Pilih Jadwal (opsional)',
      'noScheduleLink': 'Tidak terkait dengan jadwal',
      'todayAgenda': 'Agenda Hari Ini',
      'noSchedule': 'Tidak ada kegiatan kuliah',
      'scheduleDeleted': 'Jadwal berhasil dihapus',
      'createTask': 'Buat Tugas',
      'taskLinkedToSchedule': 'Tugas baru dibuat dan ditautkan ke jadwal',
      'searchNotes': 'Cari catatan...',
      'noNotes': 'Belum ada catatan',
      'noteDeleted': 'Catatan berhasil dihapus',
      'addNote': 'Tambah Catatan',
      'noteTitle': 'Judul Catatan',
      'noteTitleHint': 'Masukkan judul catatan...',
      'noteContent': 'Isi Catatan',
      'noteContentHint': 'Tulis catatan di sini...',
      'chooseNoteColor': 'Pilih Warna Catatan',
      'saveNote': 'Simpan Catatan',
      'noteSaved': 'Catatan berhasil disimpan',
      'noHabits': 'Tidak ada kebiasaan yang dilacak',
      'habitDeleted': 'Habit berhasil dihapus',
      'noTargets': 'Belum ada target mata kuliah',
      'targetDeleted': 'Target kuliah berhasil dihapus',
      'target': 'Target',
      'currentScore': 'Nilai Saat Ini',
      'targetScoreLabel': 'Sasaran',
      'reminder': 'Pengingat',
      'noReminders': 'Tidak ada pengingat aktif',
      'reminderDeleted': 'Pengingat berhasil dihapus',
      'addManual': 'Tambah manual',
      'studyTooShort': 'Sesi belajar terlalu singkat untuk disimpan',
      'studyFinished': 'Selesai Belajar',
      'duration': 'Durasi',
      'studyNotes': 'Catatan Belajar',
      'studyNotesHint': 'Mempelajari materi bab 3...',
      'cancel': 'Batal',
      'saveLog': 'Simpan Log',
      'studyDeleted': 'Sesi belajar berhasil dihapus',
      'chooseStudyTask': 'Pilih tugas belajar',
      'noTaskLink': 'Tidak terkait tugas',
      'studySubjectQuestion': 'Belajar apa hari ini?',
      'studySubjectHint': 'Contoh: Algoritma & Pemrograman',
      'studyHistory': 'Riwayat Belajar',
      'noStudyHistory': 'Belum ada riwayat sesi belajar',
      'sessionLinkedToTask': 'Sesi terkait dengan tugas baru',
      'taskNotFound': 'Tugas tidak ditemukan',
      'minutes': 'menit',
      'seconds': 'detik',
      'linkedTask': 'Terkait tugas',
      'deletedTask': 'Tugas terhapus',
      'addSchedule': 'Tambah Jadwal',
      'activityName': 'Nama Kegiatan / Kuliah',
      'scheduleTitleHint': 'Masukkan nama jadwal...',
      'location': 'Ruangan / Lokasi',
      'locationHint': 'Gedung A-302 / Zoom...',
      'lecturer': 'Dosen Pengampu',
      'lecturerHint': 'Nama dosen (opsional)...',
      'date': 'Tanggal',
      'start': 'Mulai',
      'end': 'Selesai',
      'chooseMarkerColor': 'Pilih Warna Penanda',
      'saveSchedule': 'Simpan Jadwal',
      'scheduleAdded': 'Jadwal berhasil ditambahkan',
      'addReminder': 'Tambah Pengingat',
      'reminderName': 'Nama Pengingat',
      'reminderHint': 'Belajar kalkulus / Catatan...',
      'alarmTime': 'Waktu Alarm',
      'startDate': 'Tanggal Mulai',
      'repeatReminder': 'Ulangi Pengingat',
      'saveReminder': 'Simpan Pengingat',
      'reminderSaved': 'Pengingat berhasil disimpan',
      'addTarget': 'Tambah Target',
      'courseName': 'Mata Kuliah',
      'courseHint': 'Struktur Data / Kalkulus...',
      'targetGrade': 'Target Indeks Huruf',
      'currentScoreInput': 'Nilai Sekarang',
      'targetScoreInput': 'Target Nilai Angka',
      'additionalNotes': 'Catatan Tambahan',
      'targetNotesHint': 'Tugas harian minimal 80, UAS minimal 85...',
      'saveTarget': 'Simpan Sasaran',
      'targetSaved': 'Target berhasil disimpan',
      'habitSaved': 'Habit berhasil disimpan',
      'addHabit': 'Tambah Habit',
      'habitName': 'Nama Kebiasaan',
      'habitHint': 'Membaca buku / Minum air / Olahraga...',
      'frequency': 'Frekuensi',
      'trackHabit': 'Mulai Lacak Kebiasaan',
    },
    'en': {
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'planner': 'Planner',
      'more': 'More',
      'welcomeBack': 'Welcome back to StudySync',
      'semesterProgress': 'Semester Progress',
      'keepPerformance': 'Keep up your academic performance!',
      'totalTasks': 'Total Tasks',
      'completed': 'Completed',
      'pending': 'Pending',
      'weeklyProductivity': 'Weekly Productivity',
      'plannerDesc': 'Organize and finish your daily agenda',
      'moreDesc': 'More features to support your study',
      'tasks': 'Tasks',
      'taskDesc': 'Manage assignments and college deadlines',
      'schedule': 'Schedule',
      'scheduleDesc': 'Class and activity schedule',
      'notes': 'Notes',
      'notesDesc': 'Important notes and creative ideas',
      'habits': 'Habits',
      'habitsDesc': 'Build productive daily habits',
      'courseTarget': 'Course Target',
      'studySession': 'Study Session',
      'reviewMateri': 'Material Review',
      'pomodoroShort': 'Pomodoro',
      'display': 'Display',
      'darkMode': 'Dark Mode',
      'focusSecurity': 'Notifications & Focus',
      'notifications': 'App Notifications',
      'focusMode': 'Focus Mode',
      'focusModeDesc': 'Reduce distractions during study sessions',
      'language': 'Language',
      'chooseLanguage': 'Choose Language',
      'resetDefault': 'Reset To Default',
      'profile': 'Profile',
      'username': 'Username',
      'activeSemester': 'Active Semester',
      'saveProfile': 'Save Profile',
      'pickPhoto': 'Pick Photo',
      'removePhoto': 'Remove Photo',
      'profileUpdated': 'Profile updated successfully',
      'pomodoro': 'Pomodoro Timer',
      'focusActive': 'FOCUS MODE ON',
      'focusDisabled': 'Fast forward is disabled while Focus Mode is on',
      'all': 'All',
      'noTasks': 'No tasks',
      'edit': 'Edit',
      'delete': 'Delete',
      'taskDeleted': 'Task deleted successfully',
      'addTask': 'Add Task',
      'editTask': 'Edit Task',
      'taskTitle': 'Task Title',
      'taskTitleHint': 'Enter task title...',
      'description': 'Description',
      'taskDescHint': 'Enter task details (optional)...',
      'dueDate': 'Due Date',
      'priority': 'Priority',
      'category': 'Category',
      'saveTask': 'Save Task',
      'saveChanges': 'Save Changes',
      'taskAdded': 'Task added successfully',
      'taskUpdated': 'Task updated successfully',
      'selectScheduleOptional': 'Select Schedule (optional)',
      'noScheduleLink': 'Not linked to a schedule',
      'todayAgenda': 'Today Agenda',
      'noSchedule': 'No class activities',
      'scheduleDeleted': 'Schedule deleted successfully',
      'createTask': 'Create Task',
      'taskLinkedToSchedule': 'New task created and linked to schedule',
      'searchNotes': 'Search notes...',
      'noNotes': 'No notes yet',
      'noteDeleted': 'Note deleted successfully',
      'addNote': 'Add Note',
      'noteTitle': 'Note Title',
      'noteTitleHint': 'Enter note title...',
      'noteContent': 'Note Content',
      'noteContentHint': 'Write your note here...',
      'chooseNoteColor': 'Choose Note Color',
      'saveNote': 'Save Note',
      'noteSaved': 'Note saved successfully',
      'noHabits': 'No habits tracked',
      'habitDeleted': 'Habit deleted successfully',
      'noTargets': 'No course targets yet',
      'targetDeleted': 'Course target deleted successfully',
      'target': 'Target',
      'currentScore': 'Current Score',
      'targetScoreLabel': 'Goal',
      'reminder': 'Reminder',
      'noReminders': 'No active reminders',
      'reminderDeleted': 'Reminder deleted successfully',
      'addManual': 'Add manually',
      'studyTooShort': 'Study session is too short to save',
      'studyFinished': 'Finished Studying',
      'duration': 'Duration',
      'studyNotes': 'Study Notes',
      'studyNotesHint': 'Studied chapter 3...',
      'cancel': 'Cancel',
      'saveLog': 'Save Log',
      'studyDeleted': 'Study session deleted successfully',
      'chooseStudyTask': 'Choose study task',
      'noTaskLink': 'Not linked to a task',
      'studySubjectQuestion': 'What are you studying today?',
      'studySubjectHint': 'Example: Algorithms & Programming',
      'studyHistory': 'Study History',
      'noStudyHistory': 'No study session history yet',
      'sessionLinkedToTask': 'Session linked to a new task',
      'taskNotFound': 'Task not found',
      'minutes': 'minutes',
      'seconds': 'seconds',
      'linkedTask': 'Linked task',
      'deletedTask': 'Deleted task',
      'addSchedule': 'Add Schedule',
      'activityName': 'Activity / Class Name',
      'scheduleTitleHint': 'Enter schedule name...',
      'location': 'Room / Location',
      'locationHint': 'Building A-302 / Zoom...',
      'lecturer': 'Lecturer',
      'lecturerHint': 'Lecturer name (optional)...',
      'date': 'Date',
      'start': 'Start',
      'end': 'End',
      'chooseMarkerColor': 'Choose Marker Color',
      'saveSchedule': 'Save Schedule',
      'scheduleAdded': 'Schedule added successfully',
      'addReminder': 'Add Reminder',
      'reminderName': 'Reminder Name',
      'reminderHint': 'Study calculus / Notes...',
      'alarmTime': 'Alarm Time',
      'startDate': 'Start Date',
      'repeatReminder': 'Repeat Reminder',
      'saveReminder': 'Save Reminder',
      'reminderSaved': 'Reminder saved successfully',
      'addTarget': 'Add Target',
      'courseName': 'Course',
      'courseHint': 'Data Structures / Calculus...',
      'targetGrade': 'Target Letter Grade',
      'currentScoreInput': 'Current Score',
      'targetScoreInput': 'Target Score',
      'additionalNotes': 'Additional Notes',
      'targetNotesHint': 'Daily assignments at least 80, final exam at least 85...',
      'saveTarget': 'Save Target',
      'targetSaved': 'Target saved successfully',
      'habitSaved': 'Habit saved successfully',
      'addHabit': 'Add Habit',
      'habitName': 'Habit Name',
      'habitHint': 'Read books / Drink water / Exercise...',
      'frequency': 'Frequency',
      'trackHabit': 'Start Tracking Habit',
    },
  };

  static String get(String key) {
    final language = SharedPrefService.language;
    return _values[language]?[key] ?? _values['id']?[key] ?? key;
  }
}
